//go:build !ignore_autogenerated

/*
Copyright 2025 vLLM Semantic Router.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRule) DeepCopyInto(out *ContextRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRule.
func (in *ContextRule) DeepCopy() *ContextRule {
	if in == nil {
		return nil
	}
	out := new(ContextRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationCRDFeature) DeepCopyInto(out *ConversationCRDFeature) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationCRDFeature.
func (in *ConversationCRDFeature) DeepCopy() *ConversationCRDFeature {
	if in == nil {
		return nil
	}
	out := new(ConversationCRDFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationCRDSource) DeepCopyInto(out *ConversationCRDSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationCRDSource.
func (in *ConversationCRDSource) DeepCopy() *ConversationCRDSource {
	if in == nil {
		return nil
	}
	out := new(ConversationCRDSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationSignal) DeepCopyInto(out *ConversationSignal) {
	*out = *in
	out.Feature = in.Feature
	if in.Predicate != nil {
		in, out := &in.Predicate, &out.Predicate
		*out = new(NumericPredicate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationSignal.
func (in *ConversationSignal) DeepCopy() *ConversationSignal {
	if in == nil {
		return nil
	}
	out := new(ConversationSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decision) DeepCopyInto(out *Decision) {
	*out = *in
	in.Signals.DeepCopyInto(&out.Signals)
	if in.ModelRefs != nil {
		in, out := &in.ModelRefs, &out.ModelRefs
		*out = make([]ModelRef, len(*in))
		copy(*out, *in)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]DecisionPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decision.
func (in *Decision) DeepCopy() *Decision {
	if in == nil {
		return nil
	}
	out := new(Decision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionPlugin) DeepCopyInto(out *DecisionPlugin) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionPlugin.
func (in *DecisionPlugin) DeepCopy() *DecisionPlugin {
	if in == nil {
		return nil
	}
	out := new(DecisionPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainSignal) DeepCopyInto(out *DomainSignal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainSignal.
func (in *DomainSignal) DeepCopy() *DomainSignal {
	if in == nil {
		return nil
	}
	out := new(DomainSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingSignal) DeepCopyInto(out *EmbeddingSignal) {
	*out = *in
	if in.Candidates != nil {
		in, out := &in.Candidates, &out.Candidates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrototypeScoring != nil {
		in, out := &in.PrototypeScoring, &out.PrototypeScoring
		*out = new(PrototypeScoringConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingSignal.
func (in *EmbeddingSignal) DeepCopy() *EmbeddingSignal {
	if in == nil {
		return nil
	}
	out := new(EmbeddingSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSignal) DeepCopyInto(out *EventSignal) {
	*out = *in
	if in.EventTypes != nil {
		in, out := &in.EventTypes, &out.EventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActionCodes != nil {
		in, out := &in.ActionCodes, &out.ActionCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSignal.
func (in *EventSignal) DeepCopy() *EventSignal {
	if in == nil {
		return nil
	}
	out := new(EventSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactCheckRule) DeepCopyInto(out *FactCheckRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactCheckRule.
func (in *FactCheckRule) DeepCopy() *FactCheckRule {
	if in == nil {
		return nil
	}
	out := new(FactCheckRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentPool) DeepCopyInto(out *IntelligentPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentPool.
func (in *IntelligentPool) DeepCopy() *IntelligentPool {
	if in == nil {
		return nil
	}
	out := new(IntelligentPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentPoolList) DeepCopyInto(out *IntelligentPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntelligentPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentPoolList.
func (in *IntelligentPoolList) DeepCopy() *IntelligentPoolList {
	if in == nil {
		return nil
	}
	out := new(IntelligentPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentPoolSpec) DeepCopyInto(out *IntelligentPoolSpec) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentPoolSpec.
func (in *IntelligentPoolSpec) DeepCopy() *IntelligentPoolSpec {
	if in == nil {
		return nil
	}
	out := new(IntelligentPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentPoolStatus) DeepCopyInto(out *IntelligentPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentPoolStatus.
func (in *IntelligentPoolStatus) DeepCopy() *IntelligentPoolStatus {
	if in == nil {
		return nil
	}
	out := new(IntelligentPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentRoute) DeepCopyInto(out *IntelligentRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentRoute.
func (in *IntelligentRoute) DeepCopy() *IntelligentRoute {
	if in == nil {
		return nil
	}
	out := new(IntelligentRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentRouteList) DeepCopyInto(out *IntelligentRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntelligentRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentRouteList.
func (in *IntelligentRouteList) DeepCopy() *IntelligentRouteList {
	if in == nil {
		return nil
	}
	out := new(IntelligentRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntelligentRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentRouteSpec) DeepCopyInto(out *IntelligentRouteSpec) {
	*out = *in
	in.Signals.DeepCopyInto(&out.Signals)
	if in.Decisions != nil {
		in, out := &in.Decisions, &out.Decisions
		*out = make([]Decision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentRouteSpec.
func (in *IntelligentRouteSpec) DeepCopy() *IntelligentRouteSpec {
	if in == nil {
		return nil
	}
	out := new(IntelligentRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentRouteStatus) DeepCopyInto(out *IntelligentRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = new(RouteStatistics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentRouteStatus.
func (in *IntelligentRouteStatus) DeepCopy() *IntelligentRouteStatus {
	if in == nil {
		return nil
	}
	out := new(IntelligentRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeywordSignal) DeepCopyInto(out *KeywordSignal) {
	*out = *in
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeywordSignal.
func (in *KeywordSignal) DeepCopy() *KeywordSignal {
	if in == nil {
		return nil
	}
	out := new(KeywordSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRAConfig) DeepCopyInto(out *LoRAConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRAConfig.
func (in *LoRAConfig) DeepCopy() *LoRAConfig {
	if in == nil {
		return nil
	}
	out := new(LoRAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	if in.Reasoning != nil {
		in, out := &in.Reasoning, &out.Reasoning
		*out = new(ModelReasoning)
		(*in).DeepCopyInto(*out)
	}
	if in.Pricing != nil {
		in, out := &in.Pricing, &out.Pricing
		*out = new(ModelPricing)
		(*in).DeepCopyInto(*out)
	}
	if in.LoRAs != nil {
		in, out := &in.LoRAs, &out.LoRAs
		*out = make([]LoRAConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPricing) DeepCopyInto(out *ModelPricing) {
	*out = *in
	if in.CachedInputTokenPrice != nil {
		in, out := &in.CachedInputTokenPrice, &out.CachedInputTokenPrice
		*out = new(float64)
		**out = **in
	}
	if in.CacheWriteTokenPrice != nil {
		in, out := &in.CacheWriteTokenPrice, &out.CacheWriteTokenPrice
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPricing.
func (in *ModelPricing) DeepCopy() *ModelPricing {
	if in == nil {
		return nil
	}
	out := new(ModelPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReasoning) DeepCopyInto(out *ModelReasoning) {
	*out = *in
	if in.EffortFlags != nil {
		in, out := &in.EffortFlags, &out.EffortFlags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReasoning.
func (in *ModelReasoning) DeepCopy() *ModelReasoning {
	if in == nil {
		return nil
	}
	out := new(ModelReasoning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRef) DeepCopyInto(out *ModelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRef.
func (in *ModelRef) DeepCopy() *ModelRef {
	if in == nil {
		return nil
	}
	out := new(ModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelScore) DeepCopyInto(out *ModelScore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelScore.
func (in *ModelScore) DeepCopy() *ModelScore {
	if in == nil {
		return nil
	}
	out := new(ModelScore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumericPredicate) DeepCopyInto(out *NumericPredicate) {
	*out = *in
	if in.GT != nil {
		in, out := &in.GT, &out.GT
		*out = new(float64)
		**out = **in
	}
	if in.GTE != nil {
		in, out := &in.GTE, &out.GTE
		*out = new(float64)
		**out = **in
	}
	if in.LT != nil {
		in, out := &in.LT, &out.LT
		*out = new(float64)
		**out = **in
	}
	if in.LTE != nil {
		in, out := &in.LTE, &out.LTE
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumericPredicate.
func (in *NumericPredicate) DeepCopy() *NumericPredicate {
	if in == nil {
		return nil
	}
	out := new(NumericPredicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrototypeScoringConfig) DeepCopyInto(out *PrototypeScoringConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrototypeScoringConfig.
func (in *PrototypeScoringConfig) DeepCopy() *PrototypeScoringConfig {
	if in == nil {
		return nil
	}
	out := new(PrototypeScoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStatistics) DeepCopyInto(out *RouteStatistics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStatistics.
func (in *RouteStatistics) DeepCopy() *RouteStatistics {
	if in == nil {
		return nil
	}
	out := new(RouteStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalCombination) DeepCopyInto(out *SignalCombination) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]SignalCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalCombination.
func (in *SignalCombination) DeepCopy() *SignalCombination {
	if in == nil {
		return nil
	}
	out := new(SignalCombination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalCondition) DeepCopyInto(out *SignalCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalCondition.
func (in *SignalCondition) DeepCopy() *SignalCondition {
	if in == nil {
		return nil
	}
	out := new(SignalCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Signals) DeepCopyInto(out *Signals) {
	*out = *in
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]KeywordSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Embeddings != nil {
		in, out := &in.Embeddings, &out.Embeddings
		*out = make([]EmbeddingSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainSignal, len(*in))
		copy(*out, *in)
	}
	if in.ContextRules != nil {
		in, out := &in.ContextRules, &out.ContextRules
		*out = make([]ContextRule, len(*in))
		copy(*out, *in)
	}
	if in.Structure != nil {
		in, out := &in.Structure, &out.Structure
		*out = make([]StructureSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FactCheckRules != nil {
		in, out := &in.FactCheckRules, &out.FactCheckRules
		*out = make([]FactCheckRule, len(*in))
		copy(*out, *in)
	}
	if in.Conversation != nil {
		in, out := &in.Conversation, &out.Conversation
		*out = make([]ConversationSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]EventSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Signals.
func (in *Signals) DeepCopy() *Signals {
	if in == nil {
		return nil
	}
	out := new(Signals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructureFeature) DeepCopyInto(out *StructureFeature) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructureFeature.
func (in *StructureFeature) DeepCopy() *StructureFeature {
	if in == nil {
		return nil
	}
	out := new(StructureFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructureSignal) DeepCopyInto(out *StructureSignal) {
	*out = *in
	in.Feature.DeepCopyInto(&out.Feature)
	if in.Predicate != nil {
		in, out := &in.Predicate, &out.Predicate
		*out = new(NumericPredicate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructureSignal.
func (in *StructureSignal) DeepCopy() *StructureSignal {
	if in == nil {
		return nil
	}
	out := new(StructureSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructureSource) DeepCopyInto(out *StructureSource) {
	*out = *in
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sequences != nil {
		in, out := &in.Sequences, &out.Sequences
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructureSource.
func (in *StructureSource) DeepCopy() *StructureSource {
	if in == nil {
		return nil
	}
	out := new(StructureSource)
	in.DeepCopyInto(out)
	return out
}
